from openai import OpenAI
import os, json
from dotenv import load_dotenv
load_dotenv()

endpoint = os.getenv("AZURE_OPENAI_ENDPOINT")
deployment_name = os.getenv("AZURE_OPENAI_DEPLOYMENT")
api_key = os.getenv("AZURE_OPENAI_API_KEY")

client = OpenAI(
    base_url=endpoint,
    api_key=api_key
)

def get_stock_price(symbol):
    """Get the current stock price for given symbol"""
    stock_info = {
        "symbol": symbol,
        "price": "1000"
    }
    return json.dumps(stock_info)


functions = [
    {
        "name": "get_stock_price",
        "description": "Get the current stock price for the given symbol",
        "parameters": {
            "type": "object",
            "properties": {  
                "symbol": {
                    "type": "string",
                    "description": "The symbol, e.g. AAPL",
                }
            },
            "required": ["symbol"],
        },
    }
]


response = client.chat.completions.create(
    model=os.getenv("AZURE_OPENAI_DEPLOYMENT"),  # DEPLOYMENT NAME
    messages=[
        {"role": "system", "content": "You are a helpful writer. You always follow the user's instructions carefully."},
        {"role": "user", "content": "Can you write a haiku about the sea?"},
        {"role": "user", "content": "Stock price of Microsoft?"},
    ],
    temperature=0.7,
    max_tokens=20,
    functions=functions,
    function_call="auto"  # auto is default, but we'll be explicit here
)

if response.choices[0].message.function_call:
    function_name = response.choices[0].message.function_call.name
    function_args = json.loads(response.choices[0].message.function_call.arguments)
    
    if function_name == "get_stock_price":
        function_response = get_stock_price(
            symbol=function_args.get("symbol")
        )
        
        second_response = client.chat.completions.create(
            model=os.getenv("AZURE_OPENAI_DEPLOYMENT"),  # DEPLOYMENT NAME
            messages=[
                {"role": "system", "content": "You are a helpful writer. You always follow the user's instructions carefully."},
                {"role": "user", "content": "Can you write a haiku about the sea?"},
                {"role": "user", "content": "Stock price of Microsoft?"},
                response.choices[0].message,
                {
                    "role": "function",
                    "name": function_name,
                    "content": function_response,
                },
            ],
        )
        
        print(second_response.choices[0].message)
# print(response.model_dump_json())

# tools Schema
# 1. Define a list of callable tools for the model
tools = [
    {
        "type": "function",
        "name": "get_horoscope",
        "description": "Get today's horoscope for an astrological sign.",
        "parameters": {
            "type": "object",
            "properties": {
                "sign": {
                    "type": "string",
                    "description": "An astrological sign like Taurus or Aquarius",
                },
            },
            "required": ["sign"],
        },
    },
]

def get_horoscope(sign):
    return f"{sign}: Next Tuesday you will befriend a baby otter."

# Create a running input list we will add to over time
input_list = [
    {"role": "user", "content": "What is my horoscope? I am an Aquarius."}
]

# 2. Prompt the model with tools defined
response = client.responses.create(
    model=os.getenv("AZURE_OPENAI_DEPLOYMENT"),
    tools=tools,
    input=input_list,
)

# Save function call outputs for subsequent requests
input_list += response.output

for item in response.output:
    if item.type == "function_call":
        if item.name == "get_horoscope":
            # 3. Execute the function logic for get_horoscope
            horoscope = get_horoscope(json.loads(item.arguments))
            
            # 4. Provide function call results to the model
            input_list.append({
                "type": "function_call_output",
                "call_id": item.call_id,
                "output": json.dumps({
                  "horoscope": horoscope
                })
            })

print("Final input:")
print(input_list)

response = client.responses.create(
    model=os.getenv("AZURE_OPENAI_DEPLOYMENT"),
    instructions="Respond only with a horoscope generated by a tool.",
    tools=tools,
    input=input_list,
)

# 5. The model should be able to give a response!
print("Final output:")
print(response.model_dump_json(indent=2))
print("\n" + response.output_text)