name: Lint, Test, and Deploy
on: [push,workflow_dispatch]
defaults:
    run:
      working-directory: Github_actions/05 Practice Project (Finished)
jobs: 
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Run lint
              run: npm lint
            - name: Steps Completed
              run: echo Lint completed!
    test:
        runs-on: ubuntu-latest
        needs: lint
        steps:
            - name: Get code
              uses: actions/checkout@v3
            - name: Install NodeJS
              uses: actions/setup-node@v3
              with:
                node-version: 18
            - name: Run lint
              run: npm test
            - name: Steps Completed
              run: echo Lint completed!

    Deploy:
            runs-on: ubuntu-latest
            needs: test
            steps:
                - name: Get code
                  uses: actions/checkout@v3
                - name: Install NodeJS
                  uses: actions/setup-node@v3
                  with:
                        node-version: 18
                - name: Run lint
                  run: npm build
                - name: Steps Completed
                  run: echo Deploy completed!

                

