name: Reusable workflow
on :
    workflow_call:
        inputs:
            artifact-name:
                description: name of the deployable artifacts
                required: false
                type: string
                default: dist
        outputs:
          result-outputs:
            description: result of the workflow
            value: ${{ jobs.deploy.outputs.outcome }}
        secrets:
          required-secerts:
            description: required secrets
            required: false

jobs:
    deploy:
        outputs:
          outcome: ${{steps.set-result.outputs.step-result}}
        runs-on: ubuntu-latest
        steps:
            - name: Get Code
              uses: actions/download-artifact@v3
              with:
                 name: ${{inputs.artifact-name}}
            - name: Output Information
              run: |
                echo "Deploying and uploading code......."
                echo "${{secrets.required-secerts}}"
            - name: List code
              run: ls -a
            - name: Set result output
              id: set-result
              run: echo "step-result=Success" >> $GITHUB_OUTPUT